export function canonicalToolCallKey(name: string, argumentsText: string): string;
export function compactToolArgumentsForHistory(name: string, argumentsText: string, success?: boolean): string;
export function toolResourceKey(name: string, argumentsText: string): string;
export function isPreparationOnlyTool(name: string): boolean;
export function getToolCallLimit(name: string, connectorTask: boolean): number;
export function isExplicitStopSteering(messages: string[]): boolean;
export function isExplicitPauseSteering(messages: string[]): boolean;
export function isExplicitResumeSteering(messages: string[]): boolean;
export function getDirectExecutionControl(message: string): 'pause' | 'resume' | 'stop' | null;
export function shouldHoldTaskForFeedback(message: string): boolean;
export function isActionableCapabilityCorrection(message: string): boolean;
export function resolveActionableUserGoal(message: string, previousUserMessage: string): string;
export function requiresFreshWebResearch(message: string): boolean;
export function requiresObservableExecutionEvidence(message: string): boolean;
export function buildFreshWebQuery(message: string): string;
export function isResearchOnlyRequest(message: string): boolean;
export function buildResearchFallback(userText: string, searchOutput: string, modelError?: string): string;
export function ensureResearchSourceLinks(content: string, userText: string, searchOutput: string): string;
export function extractResearchSources(searchOutput: string, limit?: number): Array<{ title: string; url: string; snippet: string }>;
export function extractRelevantResearchSources(userText: string, searchOutput: string, limit?: number): Array<{ title: string; url: string; snippet: string }>;
export function isResearchEvidenceRelevant(userText: string, searchOutput: string): boolean;
export function isResearchDeliveryDeflection(content: string): boolean;
export function isConversationOnlyMessage(message: string): boolean;
