export type TurnLifecycleStatus = 'running' | 'completed' | 'waiting_user' | 'paused' | 'checkpointed' | 'stopped' | 'failed';
export interface TurnLifecycleState {
  protocolVersion: number;
  lifecycleId: string;
  turnId: string;
  taskId: string;
  conversationId: string;
  scope: string;
  goal: string;
  deliverableType: string;
  status: TurnLifecycleStatus;
  phase: string;
  sequence: number;
  activity: string;
  progressAt: number;
  startedAt: number;
  updatedAt: number;
  finishedAt?: number;
  budget: { modelRounds: number; toolCalls: number; maxModelRounds?: number; maxToolCalls?: number };
  context: { stage: number; compactions: number; estimatedTokens: number; contextWindowTokens?: number; summary: string; unresolvedIssues: string[] };
  decisions: Array<Record<string, any>>;
  toolCalls: Array<Record<string, any>>;
  steering: Array<{ message: string; at: number; applied: boolean }>;
  events: Array<Record<string, any>>;
  recovery: { resumable: boolean; reason: string; nextAction: string };
  exit?: Record<string, any>;
}
export function sanitizeLifecycleValue(value: any, key?: string, depth?: number): any;
export function createTurnLifecycle(input?: Record<string, any>): TurnLifecycleState;
export function restoreTurnLifecycle(snapshot: unknown, input?: Record<string, any>): TurnLifecycleState;
export function recordLifecycleProgress(lifecycle: TurnLifecycleState, input?: Record<string, any>): TurnLifecycleState;
export function recordLifecycleDecision(lifecycle: TurnLifecycleState, decision?: Record<string, any>): TurnLifecycleState;
export function recordLifecycleToolStarted(lifecycle: TurnLifecycleState, input?: Record<string, any>): TurnLifecycleState;
export function recordLifecycleToolFinished(lifecycle: TurnLifecycleState, input?: Record<string, any>): TurnLifecycleState;
export function recordLifecycleContext(lifecycle: TurnLifecycleState, input?: Record<string, any>): TurnLifecycleState;
export function recordLifecycleSteering(lifecycle: TurnLifecycleState, messages: string | string[]): TurnLifecycleState;
export function synchronizeTurnLifecycle(lifecycle: TurnLifecycleState | undefined, runtime: any, finalization?: any, input?: Record<string, any>): TurnLifecycleState;
export function createLifecycleRecoveryCapsule(lifecycle: TurnLifecycleState, input?: Record<string, any>): Record<string, any>;
export function finalizeTurnLifecycle(lifecycle: TurnLifecycleState, input?: Record<string, any>): TurnLifecycleState;
export const TURN_LIFECYCLE_VERSION: number;
