import { useEffect, useMemo, useState } from 'react';
import type { Skill } from '../../types';
import { listSkills, readSkill } from '../../data/skills';

export default function SkillLibraryView() {
  const [skills, setSkills] = useState<Skill[]>([]); const [query, setQuery] = useState(''); const [selected, setSelected] = useState<Skill | null>(null); const [body, setBody] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const refresh = async () => { setLoading(true); setError(''); try { setSkills(await listSkills()); } catch (e) { setError(e instanceof Error ? e.message : '技能扫描失败'); } finally { setLoading(false); } };
  useEffect(() => { refresh(); }, []);
  const filtered = useMemo(() => skills.filter((s) => `${s.name} ${s.description} ${s.source}`.toLowerCase().includes(query.toLowerCase())), [skills, query]);
  const open = async (skill: Skill) => { setSelected(skill); setBody(''); try { setBody((await readSkill(skill.id)).content); } catch (e) { setBody(e instanceof Error ? e.message : '读取失败'); } };
  return <div style={{ flex: 1, padding: 24, overflow: 'auto' }}><div style={{ display: 'flex', gap: 8, alignItems: 'center', marginBottom: 16 }}><h2 style={{ margin: 0 }}>技能库</h2><button className="btn btn-sm" onClick={refresh} disabled={loading}>↻ 刷新</button><input className="form-input" style={{ maxWidth: 320, marginLeft: 'auto' }} value={query} onChange={(e) => setQuery(e.target.value)} placeholder="搜索技能名称、说明或来源" /></div>{error && <div className="error-banner">{error}</div>}{!loading && filtered.length === 0 && <div style={{ color: 'var(--text-muted)', padding: 40, textAlign: 'center' }}>{skills.length === 0 ? '暂无已安装技能' : '没有匹配的技能'}</div>}<div style={{ display: 'grid', gridTemplateColumns: selected ? 'minmax(280px, 1fr) minmax(360px, 1.5fr)' : 'repeat(auto-fill, minmax(260px, 1fr))', gap: 12 }}>{filtered.map((skill) => <button key={skill.id} onClick={() => open(skill)} style={{ textAlign: 'left', padding: 16, border: '1px solid var(--border-light)', background: 'var(--bg)', cursor: 'pointer' }}><div style={{ fontWeight: 600 }}>{skill.name}</div><div style={{ fontSize: 12, color: 'var(--text-secondary)', margin: '8px 0' }}>{skill.description || '暂无说明'}</div><div style={{ fontSize: 11, color: 'var(--text-muted)' }}>{skill.source}{skill.version ? ` · v${skill.version}` : ''}</div></button>)}{selected && <section style={{ borderLeft: '1px solid var(--border-light)', paddingLeft: 18 }}><div style={{ display: 'flex', justifyContent: 'space-between' }}><h3 style={{ marginTop: 0 }}>{selected.name}</h3><button className="btn btn-sm" onClick={() => setSelected(null)}>关闭</button></div><div style={{ fontSize: 12, color: 'var(--text-muted)', marginBottom: 10 }}>{selected.description || '暂无说明'} · {selected.source}</div><pre style={{ whiteSpace: 'pre-wrap', font: '12px/1.6 var(--font-mono, monospace)', maxHeight: '65vh', overflow: 'auto' }}>{body}</pre></section>}</div></div>;
}
